version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.14.0
    commands:
      - npm install
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - aws s3 sync build/ s3://strapi-codebuild
post_build:
  commands:
    - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

